#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <netinet/in.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <fcntl.h>

#include "util.h"

static int connect_to(const char *host, int port) {
    int fd = socket(AF_INET, SOCK_STREAM, 0);
    struct sockaddr_in addr; memset(&addr, 0, sizeof(addr));
    addr.sin_family = AF_INET; addr.sin_port = htons((uint16_t)port); inet_pton(AF_INET, host, &addr.sin_addr);
    if (connect(fd, (struct sockaddr*)&addr, sizeof(addr)) < 0) { perror("connect"); exit(1);} 
    return fd;
}

static int file_exists(const char *path) {
    struct stat st; return stat(path, &st) == 0 && S_ISREG(st.st_mode);
}

static long long file_size(const char *path) {
    struct stat st; if (stat(path, &st) != 0) return -1; return st.st_size;
}

static int ensure_test_file(const char *path) {
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) return -1;
    const char *msg = "TEST FILE GENERATED BY CLIENT\n";
    for (int i = 0; i < 2048; i++) {
        if (write_n(fd, msg, strlen(msg)) < 0) { close(fd); return -1; }
    }
    close(fd);
    return 0;
}

static const char *base_name(const char *path) {
    const char *s = strrchr(path, '/');
    if (!s) s = strrchr(path, '\\');
    return s ? s + 1 : path;
}

static void usage(void) {
    fprintf(stderr, "Usage: client --host 127.0.0.1 --port 9000\n");
}

static void help_commands(void) {
    fprintf(stdout, "Commands:\n");
    fprintf(stdout, "  signup <user> <pass>\n");
    fprintf(stdout, "  login <user> <pass>\n");
    fprintf(stdout, "  upload <local_path>\n");
    fprintf(stdout, "  list\n");
    fprintf(stdout, "  download <name> <out_path>\n");
    fprintf(stdout, "  delete <name>\n");
    fprintf(stdout, "  help\n");
    fprintf(stdout, "  quit\n");
}

int main(int argc, char **argv) {
    const char *host = "127.0.0.1"; int port = 9000;
    int i = 1;
    for (; i < argc; i++) {
        if (strcmp(argv[i], "--host") == 0 && i+1 < argc) host = argv[++i];
        else if (strcmp(argv[i], "--port") == 0 && i+1 < argc) port = atoi(argv[++i]);
        else break;
    }
    int fd;
    if (i < argc) {
        // One-shot mode for scripts: ./client [--host ... --port ...] <cmd> args...
        const char *cmd = argv[i++];
        fd = connect_to(host, port);
        if (strcmp(cmd, "signup") == 0) {
            if (i+1 >= argc) { usage(); return 1; }
            const char *u = argv[i++], *p = argv[i++];
            send_fmt(fd, "SIGNUP %s %s\n", u, p);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1; printf("%s\n", line);
        } else if (strcmp(cmd, "login") == 0) {
            if (i+1 >= argc) { usage(); return 1; }
            const char *u = argv[i++], *p = argv[i++];
            send_fmt(fd, "LOGIN %s %s\n", u, p);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1; printf("%s\n", line);
        } else if (strcmp(cmd, "upload") == 0) {
            if (i >= argc) { usage(); return 1; }
            const char *path = argv[i++];
            if (!file_exists(path)) { if (ensure_test_file(path) != 0) return 1; }
            long long sz = file_size(path);
            int in = open(path, O_RDONLY); if (in < 0) return 1;
            const char *name = base_name(path);
            send_fmt(fd, "UPLOAD %s %lld\n", name, sz);
            char buf[64 * 1024]; ssize_t r; while ((r = read(in, buf, sizeof(buf))) > 0) { if (write_n(fd, buf, (size_t)r) < 0) { close(in); return 1; } }
            close(in);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1; printf("%s\n", line);
        } else if (strcmp(cmd, "list") == 0) {
            send_fmt(fd, "LIST\n");
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1; printf("%s\n", line);
            int n = 0; if (sscanf(line, "OK %d", &n) == 1) { for (int k = 0; k < n; k++) { read_line(fd, line, sizeof(line)); printf("%s\n", line); } }
        } else if (strcmp(cmd, "download") == 0) {
            if (i+1 >= argc) { usage(); return 1; }
            const char *name = argv[i++]; const char *outp = argv[i++];
            send_fmt(fd, "DOWNLOAD %s\n", name);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1;
            long long sz = 0; if (sscanf(line, "OK %lld", &sz) != 1) { fprintf(stderr, "%s\n", line); return 1; }
            int out = open(outp, O_WRONLY | O_CREAT | O_TRUNC, 0644); if (out < 0) return 1;
            char buf[64 * 1024]; long long remain = sz;
            while (remain > 0) { size_t chunk = (remain > (long long)sizeof(buf)) ? sizeof(buf) : (size_t)remain; int rr = read_n(fd, buf, chunk); if (rr <= 0) { close(out); return 1; } if (write_n(out, buf, chunk) < 0) { close(out); return 1; } remain -= (long long)chunk; }
            close(out);
            fprintf(stdout, "OK\n");
        } else if (strcmp(cmd, "delete") == 0) {
            if (i >= argc) { usage(); return 1; }
            const char *name = argv[i++];
            send_fmt(fd, "DELETE %s\n", name);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) return 1; printf("%s\n", line);
        } else {
            usage();
        }
        close(fd);
        return 0;
    }
    fd = connect_to(host, port);
    help_commands();
    // Interactive loop
    char input[1024];
    for (;;) {
        fprintf(stdout, "> "); fflush(stdout);
        if (!fgets(input, sizeof(input), stdin)) break;
        // strip trailing newline
        size_t len = strlen(input); if (len > 0 && (input[len-1] == '\n' || input[len-1] == '\r')) input[--len] = '\0';
        if (len == 0) continue;
        if (strcmp(input, "quit") == 0 || strcmp(input, "exit") == 0) break;
        if (strcmp(input, "help") == 0) { help_commands(); continue; }

        char cmd[32];
        if (sscanf(input, "%31s", cmd) != 1) continue;
        if (strcmp(cmd, "signup") == 0) {
            char u[256], p[256];
            if (sscanf(input, "signup %255s %255s", u, p) != 2) { fprintf(stderr, "usage: signup <user> <pass>\n"); continue; }
            send_fmt(fd, "SIGNUP %s %s\n", u, p);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; } printf("%s\n", line);
        } else if (strcmp(cmd, "login") == 0) {
            char u[256], p[256];
            if (sscanf(input, "login %255s %255s", u, p) != 2) { fprintf(stderr, "usage: login <user> <pass>\n"); continue; }
            send_fmt(fd, "LOGIN %s %s\n", u, p);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; } printf("%s\n", line);
        } else if (strcmp(cmd, "upload") == 0) {
            char path[512];
            if (sscanf(input, "upload %511s", path) != 1) { fprintf(stderr, "usage: upload <local_path>\n"); continue; }
            if (!file_exists(path)) {
                if (ensure_test_file(path) != 0) { fprintf(stderr, "failed to create test file\n"); continue; }
            }
            long long sz = file_size(path);
            int in = open(path, O_RDONLY);
            if (in < 0) { perror("open"); continue; }
            const char *name = base_name(path);
            send_fmt(fd, "UPLOAD %s %lld\n", name, sz);
            char buf[64 * 1024]; ssize_t r;
            while ((r = read(in, buf, sizeof(buf))) > 0) {
                if (write_n(fd, buf, (size_t)r) < 0) { perror("write"); break; }
            }
            close(in);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; } printf("%s\n", line);
        } else if (strcmp(cmd, "list") == 0) {
            send_fmt(fd, "LIST\n");
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; }
            printf("%s\n", line);
            int n = 0; if (sscanf(line, "OK %d", &n) == 1) {
                for (int k = 0; k < n; k++) { read_line(fd, line, sizeof(line)); printf("%s\n", line); }
            }
        } else if (strcmp(cmd, "download") == 0) {
            char name[256], outp[512];
            if (sscanf(input, "download %255s %511s", name, outp) != 2) { fprintf(stderr, "usage: download <name> <out_path>\n"); continue; }
            send_fmt(fd, "DOWNLOAD %s\n", name);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; }
            long long sz = 0; if (sscanf(line, "OK %lld", &sz) != 1) { fprintf(stderr, "%s\n", line); continue; }
            int out = open(outp, O_WRONLY | O_CREAT | O_TRUNC, 0644);
            char buf[64 * 1024]; long long remain = sz;
            if (out < 0) {
                // Drain server payload to keep protocol in sync
                while (remain > 0) {
                    size_t chunk = (remain > (long long)sizeof(buf)) ? sizeof(buf) : (size_t)remain;
                    int rr = read_n(fd, buf, chunk);
                    if (rr <= 0) { break; }
                    remain -= (long long)chunk;
                }
                perror("open");
                continue;
            }
            //Normal streaming to file
            while (remain > 0) {
                size_t chunk = (remain > (long long)sizeof(buf)) ? sizeof(buf) : (size_t)remain;
                int rr = read_n(fd, buf, chunk);
                if (rr <= 0) { perror("read"); close(out); break; }
                if (write_n(out, buf, chunk) < 0) { perror("write"); close(out); break; }
                remain -= (long long)chunk;
            }
            close(out);
            fprintf(stdout, "OK\n");
        } else if (strcmp(cmd, "delete") == 0) {
            char name[256];
            if (sscanf(input, "delete %255s", name) != 1) { fprintf(stderr, "usage: delete <name>\n"); continue; }
            send_fmt(fd, "DELETE %s\n", name);
            char line[1024]; if (read_line(fd, line, sizeof(line)) <= 0) { perror("read"); break; } printf("%s\n", line);
        } else {
            fprintf(stderr, "unknown command\n");
        }
    }
    close(fd);
    return 0;
}


